FROM golang:1.23-alpine

WORKDIR /app

COPY . .

RUN go get -d -v ./...
RUN go build -o api/ cmd/api/*

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait 

EXPOSE 8000

CMD /wait && ./api